spring:
  datasource:
    url: jdbc:postgresql://ep-misty-mode-a5l4nn2q.us-east-2.aws.neon.tech/forumdb
    username: forumdb_owner
    password: 8dI1opaSHUFh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
